name: Deploy to ECS

on:
  workflow_run:
    workflows: ["Build and Push to ECR"]
    types: [completed]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Terraform Apply (update ECS to new image)
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    defaults:
      run:
        working-directory: app/infra

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{secrets.AWS_REGION}}
          role-session-name: github-actions-${{ github.run_number }}

      - name: Set image_uri (ECR repo + head_sha tag)
        id: image
        run: |
          ACCOUNT_ID="$(aws sts get-caller-identity --query Account --output text)"
          REGION="${{ secrets.AWS_REGION }}"
          REPO="${{ secrets.ECR_REPOSITORY }}"
          TAG="${{ github.event.workflow_run.head_sha }}"

          IMAGE_URI="${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${REPO}:${TAG}"

          echo "image_uri=${IMAGE_URI}" >> "$GITHUB_OUTPUT"
          echo "Using image_uri: ${IMAGE_URI}"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Init (S3 backend)
        run: terraform init -input=false

      - name: Terraform Plan
        run: terraform plan -input=false -var="image_uri=${{ steps.image.outputs.image_uri }}"

      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve -var="image_uri=${{ steps.image.outputs.image_uri }}"